use hoteles;

insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (40,'Hotel 1','Guatemala',3);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (40,'Hotel 2','Francia',3);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (40,'Hotel 3','Guatemala',3);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (40,'Hotel 4','Guatemala',3);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (40,'Hotel 5','Italia',3);

insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (50,'Hotel 6','Guatemala',4);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (50,'Hotel 7','Guatemala',4);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (50,'Hotel 8','Francia',4);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (50,'Hotel 9','Francia',4);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (50,'Hotel 10','Italia',4);

insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (60,'Hotel 11','Italia',5);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (60,'Hotel 12','Francia',5);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (60,'Hotel 13','Francia',5);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (60,'Hotel 14','Italia',5);
insert into hotel(CantidadDisponible,Nombre,Pais,Estrellas) values (60,'Hotel 15','Italia',5);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,1);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,1);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,1);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,1);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,1);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,1);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,1);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,1);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,2);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,2);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,2);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,2);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,2);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,2);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,2);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,2);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,3);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,3);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,3);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,3);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,3);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,3);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,3);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,3);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,4);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,4);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,4);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,4);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,4);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,4);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,4);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,4);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,5);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,5);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,5);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,5);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,5);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,5);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,5);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,5);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,6);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,6);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,6);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,6);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,6);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,6);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,6);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,6);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,7);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,7);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,7);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,7);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,7);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,7);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,7);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,7);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,8);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,8);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,8);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,8);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,8);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,8);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,8);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,8);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,9);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,9);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,9);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,9);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,9);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,9);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,9);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,9);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,10);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,10);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,10);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,10);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,10);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,10);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,10);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,10);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,11);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,11);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,11);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,11);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,11);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,11);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,11);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,11);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,12);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,12);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,12);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,12);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,12);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,12);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,12);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,12);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,13);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,13);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,13);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,13);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,13);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,13);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,13);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,13);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,14);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,14);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,14);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,14);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,14);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,14);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,14);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,14);

insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,15);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,15);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,15);
insert into habitacion(Tipo,Estado,IdHotel) values('Simple',false,15);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,15);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,15);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,15);
insert into habitacion(Tipo,Estado,IdHotel) values('Individual',false,15);


insert into cliente(Nombre,Apellido) values ('Alfonso','Borras');
insert into cliente(Nombre,Apellido) values ('Olaya','Barbero');
insert into cliente(Nombre,Apellido) values ('Josefina','Arnaiz');
insert into cliente(Nombre,Apellido) values ('Eugenio','Frances');
insert into cliente(Nombre,Apellido) values ('Brahim','Fidalgo');
insert into cliente(Nombre,Apellido) values ('Soraya','Escribano');
insert into cliente(Nombre,Apellido) values ('Francisca','Martinez');
insert into cliente(Nombre,Apellido) values ('Nacho','Cano');
insert into cliente(Nombre,Apellido) values ('Alicia','Duarte');
insert into cliente(Nombre,Apellido) values ('Dionisio','Aragon');

insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(1,1,1,'2019-07-15');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,1,2,'2018-02-18');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(5,1,3,'2020-03-27');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(6,1,4,'2020-04-06');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,1,5,'2019-05-14');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(7,1,6,'2020-06-25');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(3,1,7,'2020-07-02');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(8,1,8,'2019-12-25');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(2,1,9,'2019-09-21');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(9,1,10,'2018-10-12');

insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(1,2,11,'2020-01-12');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,2,12,'2019-02-28');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(5,2,13,'2018-05-10');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(6,2,14,'2019-04-16');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,2,15,'2020-05-04');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(7,2,1,'2019-06-15');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(3,2,2,'2018-07-12');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(8,2,3,'2020-08-13');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(2,2,4,'2019-09-15');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(9,2,5,'2020-10-16');

insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(1,3,6,'2020-11-02');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(3,3,7,'2020-02-25');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(5,3,8,'2019-05-10');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(6,3,9,'2020-04-26');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,3,10,'2019-05-16');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(7,3,11,'2018-06-05');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(3,3,12,'2020-07-29');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(8,3,13,'2020-08-22');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(2,3,14,'2018-09-15');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(9,3,15,'2019-10-22');

insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(1,4,1,'2020-11-02');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,4,2,'2019-12-14');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(5,4,3,'2018-11-27');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(6,4,4,'2020-04-26');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,4,5,'2019-05-16');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(7,4,6,'2020-06-05');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(3,4,7,'2019-07-29');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(8,4,8,'2018-08-22');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(2,4,9,'2020-09-24');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(9,4,10,'2019-10-22');

insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(1,5,11,'2020-11-02');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,5,12,'2019-05-10');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(5,5,13,'2018-11-27');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(6,5,14,'2020-04-26');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,5,15,'2020-05-16');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(7,5,1,'2020-09-15');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(3,5,2,'2019-07-29');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(8,5,3,'2018-08-22');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(2,5,4,'2019-05-10');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(9,5,5,'2020-10-22');

insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(1,6,6,'2020-11-02');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(1,6,7,'2020-12-05');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(5,6,8,'2019-11-27');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(6,6,9,'2018-04-26');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,6,10,'2020-05-10');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(7,6,11,'2019-06-05');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(3,6,12,'2018-07-29');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(8,6,13,'2019-08-22');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(2,6,14,'2020-09-15');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(9,6,15,'2019-10-22');

insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(1,7,1,'2020-11-02');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(7,7,2,'2019-09-15');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(5,7,3,'2020-05-10');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(6,7,4,'2018-04-26');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,7,5,'2020-05-16');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(7,7,6,'2019-06-05');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(3,7,7,'2020-07-29');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(8,7,8,'2018-08-22');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(2,7,9,'2019-09-24');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(9,7,10,'2020-10-22');

insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(1,8,11,'2019-11-02');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,8,12,'2020-12-25');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(5,8,13,'2020-11-27');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(6,8,14,'2020-04-26');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,8,15,'2019-05-10');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(7,8,1,'2018-06-05');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(3,8,2,'2019-07-29');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(8,8,3,'2020-08-22');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(2,8,4,'2019-09-24');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(9,8,5,'2018-10-22');

insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(1,9,6,'2019-11-02');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(2,9,7,'2018-12-25');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(5,9,8,'2019-07-15');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(6,9,9,'2019-04-26');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,9,10,'2018-05-16');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(7,9,11,'2020-06-05');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(3,9,12,'2019-07-29');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(8,9,13,'2018-08-22');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(2,9,14,'2020-05-10');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(9,9,15,'2019-10-22');

insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(1,10,1,'2019-11-02');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(9,10,2,'2018-12-25');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(5,10,3,'2019-11-27');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(6,10,4,'2018-04-26');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(4,10,5,'2020-05-16');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(7,10,6,'2018-06-05');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(3,10,7,'2020-09-15');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(8,10,8,'2018-05-10');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(2,10,9,'2019-09-24');
insert into reservacion(IdHabitacion,IdCliente,IdHotel,Fecha) values(9,10,10,'2020-10-22');

insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(1,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(2,"14:20:10","09:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(3,"15:10:10","10:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(4,"13:40:10","14:30:10",200);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(5,"20:50:10","10:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(6,"15:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(7,"17:34:10","16:30:10",250);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(8,"16:23:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(9,"17:40:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(10,"18:11:10","05:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(11,"17:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(12,"13:30:10","07:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(13,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(14,"13:30:10","17:30:10",300);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(15,"13:30:10","16:30:10",200);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(16,"13:30:10","10:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(17,"13:30:10","09:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(18,"13:30:10","08:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(19,"13:30:10","07:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(20,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(21,"13:30:10","16:30:10",200);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(22,"13:30:10","19:30:10",350);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(23,"13:30:10","04:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(24,"13:30:10","06:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(25,"13:30:10","10:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(26,"13:30:10","01:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(27,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(28,"13:30:10","10:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(29,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(30,"13:30:10","04:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(31,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(32,"13:30:10","10:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(33,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(34,"13:30:10","19:30:10",350);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(35,"13:30:10","06:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(36,"13:30:10","21:30:10",450);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(37,"13:30:10","02:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(38,"13:30:10","01:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(39,"13:30:10","02:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(40,"13:30:10","10:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(41,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(42,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(43,"13:30:10","09:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(44,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(45,"13:30:10","03:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(46,"13:30:10","06:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(47,"13:30:10","05:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(48,"13:30:10","15:30:10",150);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(49,"13:30:10","18:30:10",300);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(50,"13:30:10","10:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(51,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(52,"13:30:10","04:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(53,"13:30:10","05:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(54,"13:30:10","06:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(55,"13:30:10","08:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(56,"13:30:10","17:30:10",250);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(57,"13:30:10","16:30:10",200);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(58,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(59,"13:30:10","04:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(60,"13:30:10","10:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(61,"13:30:10","02:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(62,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(63,"13:30:10","18:30:10",400);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(64,"13:30:10","19:30:10",450);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(65,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(66,"13:30:10","10:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(67,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(68,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(69,"13:30:10","07:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(70,"13:30:10","05:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(71,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(72,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(73,"13:30:10","17:30:10",350);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(74,"13:30:10","16:30:10",300);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(75,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(76,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(77,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(78,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(79,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(80,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(81,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(82,"13:30:10","17:30:10",350);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(83,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(84,"15:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(85,"18:30:10","18:30:10",400);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(86,"17:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(87,"16:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(88,"14:30:10","04:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(89,"16:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(90,"14:30:10","08:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(91,"22:30:10","06:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(92,"13:30:10","19:30:10",450);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(93,"21:30:10","06:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(94,"13:30:10","11:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(95,"20:30:10","10:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(96,"19:30:10","18:30:10",400);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(97,"17:30:10","08:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(98,"15:30:10","06:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(99,"16:30:10","04:30:10",0);
insert into registro(IdReservacion,Checkin,CheckOut, Mora) values(100,"14:30:10","02:30:10",0);